### ISSUE TITLE
Native solution for iOS 15 users

### ISSUE THREAD

**Issue by kesenwang** [billylo1/covidpass#4]
Just wanted to throw this in here as well, I’m not sure if this is limited right now to only iOS 15 users as I don’t have another device not running beta, but simply long-pressing and choosing to open the QR card in Apple Health will store your immunization records, QR code and signature verifications in health.

![DBB6C0D6-23ED-4429-A6E9-2007D43A6202](https://user-images.githubusercontent.com/86499245/132658682-1bc1676a-d6de-4ca6-82f7-9f576db0bf07.jpeg)
![A205DC86-E3EF-4887-B827-DE467EFFA029](https://user-images.githubusercontent.com/86499245/132658689-66a876b5-49ae-4435-b8c6-0dba5c0a2400.png)
![EBBC854E-AAAE-4472-9170-7CFFBB1731F1](https://user-images.githubusercontent.com/86499245/132658694-60135cf0-d650-49b2-9d62-b749ebca7978.jpeg)

**Comment by billylo1** [comment]
thanks!  I upgraded one of my phone to iOS 15.1 and tested this successfully with BC's vaccine pass.  It should work with Ontario's as well when it starts to offer one... this is great news.  Just need Google to step up and follow suit.
