### ISSUE TITLE
Restricted to Android 8

### ISSUE THREAD

**Issue by ToniCipriani** [billylo1/covidpass#51]
Official Google docs say this should be supported for Android 5+, why is the site restricted to 8.1?

https://support.google.com/googlepay/answer/10890261?hl=en#zippy=%2Ccant-add-your-covid-card

**Comment by ToniCipriani** [comment]
Also this is not working for Android 8.1 either. The welcome text would ask me to try the Gpay button, but the actual button would be locked out saying I need 8.1+.
![Screenshot_20220116-200519](https://user-images.githubusercontent.com/2412685/149686012-23f62dac-91c9-4310-b218-455182e4ace2.png)
![Screenshot_20220116-200527](https://user-images.githubusercontent.com/2412685/149686014-7abbd34a-9d4c-4c76-8aff-56f0db109811.png)
![Screenshot_20220116-200533](https://user-images.githubusercontent.com/2412685/149686015-635bbd44-ddc9-4fb9-be98-96b80f501720.png)

**Comment by billylo1** [comment]
fixed... thx for the PR!
