### ISSUE TITLE
The passbook button works on Firefox and Edge (Windows 10) but is disabled

### ISSUE THREAD

**Issue by hdpinto** [billylo1/covidpass#7]
After removing `disabled=true` from the submit button using dev tools, the pkpass file was still created and I was able to load it onto my phone successfully.

I would recommend not arbitrarily restricting browsers since these passes work on several apps for android as well, and not everyone uses or wants to use chrome. I was able to find this workaround and still get my pass on my android phone (no chrome installed), but if possible I would suggest the button not be disabled unless there is a functional reason not to enable it.

**Comment by straxus** [comment]
We've loosened up the rules around this to give people more chances to save this - I believe this resolves the issue noted above.
