### ISSUE TITLE
Add to Wallet disabled

### ISSUE THREAD

**Issue by sumitthapar-ca** [billylo1/covidpass#8]
Add to Wallet seem to be disabled. BTW, am on iOS 15

![image](https://user-images.githubusercontent.com/48067702/134419243-b5982271-372a-4339-86c0-28ed67036fa2.png)

**Comment by MattDemers** [comment]
I had to open it as an email attachment, and it added properly for me there. From the file itself, it didn't give me the option.

**Comment by sumitthapar-ca** [comment]
> I had to open it as an email attachment, and it added properly for me there. From the file itself, it didn't give me the option.

Just Shows me an option for select file. How do you open it as email attachment?￼

**Comment by MattDemers** [comment]
> > I had to open it as an email attachment, and it added properly for me there. From the file itself, it didn't give me the option.
> 
> Just Shows me an option for select file. How do you open it as email attachment?￼

I did the process on Desktop, which gave me a .pkpass file. I then emailed that to myself.

**Comment by straxus** [comment]
This issue should now be resolved in the latest version of the app - can you please try again, and reopen this if it's still an issue?
